name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump2version twine wheel

    - name: Set up Git user
      run: |
        git config user.email ${{ secrets.EMAIL }}
        git config user.name ${{ secrets.USERNAME }}

    - name: Bump version
      id: bump-version
      run: |
        bump2version patch --tag
        echo "::set-output name=NEW_VERSION::$(cat VERSION)"

    - name: Push changes
      run: |
        git push origin HEAD:main
        git push --tags

    - name: Build and deploy
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
